spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    timeout: 5000 # 连接超时时间（毫秒）
    #redis 连接池配置
    pool-config:
      max-total: 256 #池中最大链接数
      max-idle: 128 # 连接池中的最大空闲连接
      min-idle: 8 # 连接池中的最小空闲连接
      max-wait-millis: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      test-on-borrow: false # 调用者获取链接时，是否检测当前链接有效性
      test-on-return: false # 向链接池中归还链接时，是否检测链接有效性
      test-while-idle: true  # 调用者获取链接时，是否检测空闲超时, 如果超时，则会被移除-
      num-tests-per-eviction-run: 8 # 空闲链接检测线程一次运行检测多少条链接
      time-between-eviction-runs-millis: 60000 # 空闲链接检测线程检测周期。如果为负值，表示不运行检测线程。（单位：毫秒，默认为-1）
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒