## MyBatis 的配置
mybatis:
  type-aliases-package: com.orainge.wenwen.model # 设置别名，具体为数据表实体类所在的包
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:config/mapper/*Mapper.xml